### ISSUE TITLE
pip install failed with release [0.1.0]

### ISSUE THREAD

**Issue by virginiayung** [mapbox/rio-pansharpen#15]
#### Problem:
Pip install failed with 
```IOError: [Errno 2] No such file or directory: 'README.md'```

#### Command:
```
pip install rio-pansharpen
```

#### Full backtrace:

```
$pip install rio-pansharpen
Collecting rio-pansharpen
  Downloading rio-pansharpen-0.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mp/nl3vzcd93979ktmr6rxtt48r0000gn/T/pip-build-fxrufF/rio-pansharpen/setup.py", line 6, in <module>
        with codecs_open('README.md', encoding='utf-8') as f:
      File "/Users/VirginiaMapbox/venv/lib/python2.7/codecs.py", line 896, in open
        file = __builtin__.open(filename, mode, buffering)
    IOError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/mp/nl3vzcd93979ktmr6rxtt48r0000gn/T/pip-build-fxrufF/rio-pansharpen/

```

### Current fix implemented in `0.1.1`:
I should have used README.rst in the setup.py instead of the markdown file. For release`[0.1.1]`, I removed `setup.cfg` which tells PyPI where my README file is:
```
[metadata]
description-file = README.md
```
I was able to run `pip install rio-pansharpen` successfully after this change. For the next release, I will include README.rst as well as try to add the README files to `MANIFEST.in`.

**Comment by virginiayung** [comment]
[README.rst](https://github.com/mapbox/rio-pansharpen/blob/master/README.rst) added in commit [8dc1216](https://github.com/mapbox/rio-pansharpen/commit/8dc1216fb16725f19df08f7e32e108365762296f).

**Comment by perrygeo** [comment]
If we're going with `README.rst`, we should also delete `README.md` to avoid confusion
